using Microsoft.Extensions.Logging;
using HmacManager.Caching;

namespace HmacManager.Diagnostics;

/// <summary>
/// The complete catalogue of log messages emitted by HmacManager.
/// </summary>
/// <remarks>
///     <para>
///         Keeping every message in one place makes the library's diagnostic surface reviewable as a
///         unit — event ids stay unique, levels stay consistent, and it is possible to verify at a
///         glance that no message can leak a private key. Call sites stay a single line, so the
///         signing and verification paths read as the algorithms they are rather than as logging code.
///     </para>
///     <para>
///         Messages are generated by the <c>[LoggerMessage]</c> source generator, so each one compiles
///         to a cached delegate with a compile-time level check: a disabled message costs a single
///         <c>IsEnabled</c> call and allocates nothing.
///     </para>
///     <para>
///         Event ids are grouped by area and are part of the library's contract — existing ids are
///         never reused for a different meaning:
///     </para>
///     <list type="table">
///         <item><term>1000–1099</term><description>Signing (outbound requests).</description></item>
///         <item><term>1100–1199</term><description>Verification (inbound requests).</description></item>
///         <item><term>1200–1299</term><description>Policy resolution and configuration reload.</description></item>
///         <item><term>1300–1399</term><description>The ASP.NET Core authentication pipeline.</description></item>
///     </list>
///     <para>
///         Levels follow the convention that a library is a guest in someone else's log stream:
///         <c>Information</c> is reserved for events an operator would want in production without
///         opting in (a policy set changing underneath a running process), <c>Warning</c> for a
///         recognized signing attempt that was rejected (expired, replayed, mismatched) and for
///         server-side faults, <c>Debug</c> for per-request outcomes and for unrecognized input a
///         caller can send unbounded (no header, unparseable headers, an unknown policy name), and
///         <c>Trace</c> for the signing material needed to diagnose a signature mismatch.
///     </para>
/// </remarks>
internal static partial class HmacLog
{
    // ---------------------------------------------------------------------------------------------
    // Signing — 1000–1099
    // ---------------------------------------------------------------------------------------------

    /// <summary>
    /// Records that an outgoing request was signed and the HMAC headers were attached.
    /// </summary>
    [LoggerMessage(
        EventId = 1000,
        Level = LogLevel.Debug,
        Message = "Signed {Method} {Uri} with policy \"{Policy}\", scheme \"{Scheme}\" and nonce {Nonce}.")]
    public static partial void RequestSigned(
        ILogger logger, HttpMethod method, Uri? uri, string policy, string? scheme, Guid nonce);

    /// <summary>
    /// Records that signing produced no HMAC, so the request cannot be sent with credentials.
    /// </summary>
    [LoggerMessage(
        EventId = 1001,
        Level = LogLevel.Warning,
        Message = "Signing produced no HMAC for {Method} {Uri} with policy \"{Policy}\" and scheme \"{Scheme}\". The request has not been signed.")]
    public static partial void SigningFailed(
        ILogger logger, HttpMethod method, Uri? uri, string policy, string? scheme);

    /// <summary>
    /// Records the exact string that was hashed to produce the signature.
    /// </summary>
    /// <remarks>
    /// The signing content never contains the private key, but it does contain the public key, the
    /// nonce and any scheme header values — which may carry user identifiers. It is logged at
    /// <see cref="LogLevel.Trace"/> so it is opt-in and off by default.
    /// </remarks>
    [LoggerMessage(
        EventId = 1002,
        Level = LogLevel.Trace,
        Message = "Signing content for policy \"{Policy}\": {SigningContent}")]
    public static partial void SigningContentComputed(
        ILogger logger, string policy, string? signingContent);

    /// <summary>
    /// Records that an outgoing request was abandoned because it could not be signed.
    /// </summary>
    [LoggerMessage(
        EventId = 1003,
        Level = LogLevel.Warning,
        Message = "Not sending {Method} {Uri}: the request could not be signed.")]
    public static partial void OutboundRequestNotSent(ILogger logger, HttpMethod method, Uri? uri);

    // ---------------------------------------------------------------------------------------------
    // Verification — 1100–1199
    // ---------------------------------------------------------------------------------------------

    /// <summary>
    /// Records that an inbound request carried a valid, unexpired, non-replayed signature.
    /// </summary>
    [LoggerMessage(
        EventId = 1100,
        Level = LogLevel.Debug,
        Message = "Verified {Method} {Uri} against policy \"{Policy}\" and scheme \"{Scheme}\".")]
    public static partial void RequestVerified(
        ILogger logger, HttpMethod method, Uri? uri, string policy, string? scheme);

    /// <summary>
    /// Records that the request did not carry every header the configured scheme requires, so no
    /// signature could be reconstructed.
    /// </summary>
    [LoggerMessage(
        EventId = 1101,
        Level = LogLevel.Warning,
        Message = "Rejected {Method} {Uri}: the request is missing one or more headers required by scheme \"{Scheme}\" of policy \"{Policy}\".")]
    public static partial void VerificationHeadersMissing(
        ILogger logger, HttpMethod method, Uri? uri, string policy, string? scheme);

    /// <summary>
    /// Records that the request was signed too long ago to still be accepted.
    /// </summary>
    [LoggerMessage(
        EventId = 1102,
        Level = LogLevel.Warning,
        Message = "Rejected a request for policy \"{Policy}\": signed at {DateRequested:o}, which is outside the {MaxAgeInSeconds}s window. Check for clock skew between the caller and this host.")]
    public static partial void VerificationRequestExpired(
        ILogger logger, string policy, DateTimeOffset dateRequested, int maxAgeInSeconds);

    /// <summary>
    /// Records that a nonce was presented twice — either a replay attempt or a client retry.
    /// </summary>
    [LoggerMessage(
        EventId = 1103,
        Level = LogLevel.Warning,
        Message = "Rejected a request for policy \"{Policy}\": nonce {Nonce} has already been used. This is a replayed request.")]
    public static partial void VerificationNonceReplayed(ILogger logger, string policy, Guid nonce);

    /// <summary>
    /// Records that the recomputed signature did not match the one on the request.
    /// </summary>
    [LoggerMessage(
        EventId = 1104,
        Level = LogLevel.Warning,
        Message = "Rejected a request for policy \"{Policy}\" and scheme \"{Scheme}\": the recomputed signature does not match the signature presented by the caller. Enable Trace logging for \"HmacManager\" to compare the signing content.")]
    public static partial void VerificationSignatureMismatch(
        ILogger logger, string policy, string? scheme);

    /// <summary>
    /// Records both signatures and the signing content behind a mismatch.
    /// </summary>
    /// <remarks>
    /// This is the message that turns "401, no idea why" into a diagnosis: a mismatch is almost
    /// always a difference in the signing content (a relative URI, a proxy rewriting the host, a
    /// body read twice). Logged at <see cref="LogLevel.Trace"/> for the reasons given on
    /// <see cref="SigningContentComputed"/>.
    /// </remarks>
    [LoggerMessage(
        EventId = 1105,
        Level = LogLevel.Trace,
        Message = "Signature mismatch for policy \"{Policy}\". Recomputed {ComputedSignature} from signing content {SigningContent}; the caller presented {PresentedSignature}.")]
    public static partial void VerificationSignatureMismatchDetail(
        ILogger logger, string policy, string? computedSignature, string? signingContent, string? presentedSignature);

    // ---------------------------------------------------------------------------------------------
    // Policies and configuration — 1200–1299
    // ---------------------------------------------------------------------------------------------

    /// <summary>
    /// Records a request for a policy name that is not registered.
    /// </summary>
    /// <remarks>
    /// Debug, not Warning: the policy name is caller-supplied — in the ext-authz service it comes
    /// straight off a request header — so an unknown name is routine, unbounded input (a probe or a
    /// misconfigured client), not a server-side fault. Logging it at Warning would let a caller drive
    /// unbounded Warning volume. The real outcome is the null manager the caller already handles (or
    /// the exception a DI-wired consumer already throws), so this line is diagnostic only.
    /// </remarks>
    [LoggerMessage(
        EventId = 1200,
        Level = LogLevel.Debug,
        Message = "No HMAC policy named \"{Policy}\" is registered.")]
    public static partial void PolicyNotFound(ILogger logger, string policy);

    /// <summary>
    /// Records that a policy names a nonce cache that was never registered, which would otherwise
    /// surface only as an unexplained null manager.
    /// </summary>
    [LoggerMessage(
        EventId = 1201,
        Level = LogLevel.Warning,
        Message = "Policy \"{Policy}\" requires the {CacheType} nonce cache, which is not registered.")]
    public static partial void NonceCacheNotFound(ILogger logger, string policy, NonceCacheType cacheType);

    /// <summary>
    /// Records a request for a scheme the named policy does not declare.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Debug for the same reason as <see cref="PolicyNotFound"/>: the scheme name is caller-supplied
    /// and unbounded, so a Warning here would let a caller drive Warning volume at will.
    /// </para>
    /// <para>
    /// This exists because the alternative was worse than a null manager. The scheme used to be
    /// looked up without checking the result, so an unresolved name produced a working manager that
    /// signed <em>without</em> the scheme — no scheme header, and none of its header values in the
    /// signing content — which the verifier then rejected as a signature mismatch. A typo in a
    /// scheme name and a genuinely wrong key were indistinguishable from the outside.
    /// </para>
    /// </remarks>
    [LoggerMessage(
        EventId = 1202,
        Level = LogLevel.Debug,
        Message = "Policy \"{Policy}\" does not declare a scheme named \"{Scheme}\".")]
    public static partial void SchemeNotFound(ILogger logger, string policy, string scheme);

    /// <summary>
    /// Records that the library is watching configuration for policy changes.
    /// </summary>
    [LoggerMessage(
        EventId = 1210,
        Level = LogLevel.Information,
        Message = "Watching configuration for HMAC policy changes. {PolicyCount} policies are active: {Policies}.")]
    public static partial void PolicyReloadWatchStarted(ILogger logger, int policyCount, string policies);

    /// <summary>
    /// Records that a configuration change replaced the live policy set. This is
    /// <see cref="LogLevel.Information"/> because a key rotation silently taking effect is exactly
    /// the kind of event an operator needs to correlate against later.
    /// </summary>
    [LoggerMessage(
        EventId = 1211,
        Level = LogLevel.Information,
        Message = "Reloaded HMAC policies from configuration. {PolicyCount} policies are now active: {Policies}.")]
    public static partial void PolicyReloadSucceeded(ILogger logger, int policyCount, string policies);

    /// <summary>
    /// Records that a configuration change could not be applied and the previous policy set is
    /// still serving requests.
    /// </summary>
    /// <remarks>
    /// Transient during a rotation, because a ConfigMap and its Secret do not land at the same
    /// instant. Persistent means the mounted configuration is wrong and keys are stale — which is
    /// otherwise invisible, since requests keep succeeding against the old key.
    /// </remarks>
    [LoggerMessage(
        EventId = 1212,
        Level = LogLevel.Warning,
        Message = "Could not apply an HMAC policy configuration change; keeping the previous {PolicyCount} policies. This is expected while a key rotation is only partially visible, but repeated occurrences mean the configuration is invalid.")]
    public static partial void PolicyReloadFailed(ILogger logger, int policyCount, Exception exception);

    // ---------------------------------------------------------------------------------------------
    // Authentication pipeline — 1300–1399
    // ---------------------------------------------------------------------------------------------

    /// <summary>
    /// Records that a request carried no HMAC authorization header, so the handler deferred to any
    /// other configured authentication scheme.
    /// </summary>
    [LoggerMessage(
        EventId = 1300,
        Level = LogLevel.Debug,
        Message = "No HMAC authorization header on {Method} {Path}; deferring to other authentication schemes.")]
    public static partial void AuthenticationSkipped(ILogger logger, string method, string path);

    /// <summary>
    /// Records that the application's <c>OnValidateKeys</c> handler rejected the credentials.
    /// </summary>
    [LoggerMessage(
        EventId = 1301,
        Level = LogLevel.Warning,
        Message = "HMAC authentication rejected for policy \"{Policy}\": the OnValidateKeys event returned false.")]
    public static partial void KeyValidationRejected(ILogger logger, string policy);

    /// <summary>
    /// Records a successful authentication, including the claims minted for the caller.
    /// </summary>
    [LoggerMessage(
        EventId = 1302,
        Level = LogLevel.Debug,
        Message = "HMAC authentication succeeded for policy \"{Policy}\" and scheme \"{Scheme}\" with {ClaimCount} claims.")]
    public static partial void AuthenticationSucceeded(
        ILogger logger, string policy, string? scheme, int claimCount);

    /// <summary>
    /// Records a failed authentication. The reason was already logged by the verification path.
    /// </summary>
    [LoggerMessage(
        EventId = 1303,
        Level = LogLevel.Warning,
        Message = "HMAC authentication failed for policy \"{Policy}\".")]
    public static partial void AuthenticationFailed(ILogger logger, string policy);

    /// <summary>
    /// Records that a caller named a policy this host does not have. Distinct from
    /// <see cref="PolicyNotFound"/> only in vantage point — this fires from the authentication
    /// context provider — but the same reasoning applies: the policy name is caller-supplied and
    /// unbounded, so it is Debug, not Warning, and the caller receives a rejection either way.
    /// </summary>
    [LoggerMessage(
        EventId = 1310,
        Level = LogLevel.Debug,
        Message = "A request presented HMAC policy \"{Policy}\", which is not registered on this host.")]
    public static partial void RequestedPolicyNotRegistered(ILogger logger, string policy);
}
