using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using HmacManager.Components;
using HmacManager.Headers;
using HmacManager.Policies;

namespace Unit.Tests.Components.SigningContent;

/// <summary>
/// The other half of client/lib/test/signing-parity.test.ts. Both read
/// test/fixtures/signing-parity.json and must reproduce the same strings from the same
/// inputs.
/// </summary>
/// <remarks>
/// This is the only thing that holds the two implementations to one wire format. Every
/// other test in either suite signs and verifies within a single implementation, so an
/// implementation could drift into being perfectly self-consistent and unable to talk to
/// the other — which is exactly what had happened before this existed: the signing
/// content was hashed as UTF-8 here and as one byte per code unit in TypeScript, and the
/// two produced different signatures for any request whose scheme headers carried a
/// non-ASCII character. Nothing failed, because nothing compared them.
///
/// The fixture is generated by test/fixtures/gen-signing-parity.mjs, which shares no code
/// with either implementation. Regenerating it after changing one of them would defeat
/// the point; a case is added by hand and the fixture regenerated only then.
/// </remarks>
[TestFixture]
public class Test_SigningContentParity
{
    public static IEnumerable<ParityCase> Cases => LoadCases();

    [TestCaseSource(nameof(Cases))]
    public async Task Test_SigningContent_Matches_The_Fixture(ParityCase testCase)
    {
        var (signingContent, _) = await ComputeAsync(testCase);
        Assert.That(signingContent, Is.EqualTo(testCase.SigningContent), testCase.Description);
    }

    [TestCaseSource(nameof(Cases))]
    public async Task Test_Signature_Matches_The_Fixture(ParityCase testCase)
    {
        var (_, signature) = await ComputeAsync(testCase);
        Assert.That(signature, Is.EqualTo(testCase.Signature), testCase.Description);
    }

    private static async Task<(string SigningContent, string Signature)> ComputeAsync(ParityCase testCase)
    {
        var provider = new HmacSignatureProvider(new HmacSignatureProviderOptions
        {
            Algorithms = new Algorithms
            {
                ContentHashAlgorithm = testCase.ContentHashAlgorithmValue,
                SigningHashAlgorithm = testCase.SigningHashAlgorithmValue
            },
            Keys = new KeyCredentials
            {
                PublicKey = Guid.Parse(testCase.PublicKey),
                PrivateKey = testCase.PrivateKey
            },
            ContentHashGenerator = new ContentHashGenerator(testCase.ContentHashAlgorithmValue),
            SignatureHashGenerator = new SignatureHashGenerator(
                testCase.PrivateKey, testCase.SigningHashAlgorithmValue)
        });

        var request = new HttpRequestMessage(new HttpMethod(testCase.Method), testCase.Url);
        if (testCase.Body is not null)
        {
            request.Content = new StringContent(testCase.Body, Encoding.UTF8);
        }

        foreach (var headerValue in testCase.HeaderValues)
        {
            request.Headers.TryAddWithoutValidation(headerValue.Name, headerValue.Value);
        }

        var headerValues = testCase.HeaderValues
            .Select(headerValue => new HeaderValue(headerValue.Name, headerValue.Value))
            .ToArray();

        var signingContent = await provider.ComputeSigningContentAsync(
            request,
            DateTimeOffset.FromUnixTimeMilliseconds(testCase.DateRequestedMs),
            Guid.Parse(testCase.Nonce),
            headerValues);

        return (signingContent, await provider.ComputeSignatureAsync(signingContent));
    }

    private static IEnumerable<ParityCase> LoadCases()
    {
        // Copied next to the assembly by Unit.csproj — the fixture lives at
        // test/fixtures/ because it belongs to neither suite.
        var path = Path.Combine(
            TestContext.CurrentContext.TestDirectory, "fixtures", "signing-parity.json");

        var fixture = JsonSerializer.Deserialize<ParityFixture>(File.ReadAllText(path),
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

        // An empty or unreadable fixture would otherwise make every case vacuously pass.
        Assert.That(fixture?.Cases, Is.Not.Null.And.Not.Empty,
            $"The parity fixture at \"{path}\" is missing or empty.");

        return fixture!.Cases;
    }

    public class ParityFixture
    {
        public List<ParityCase> Cases { get; set; } = [];
    }

    public class ParityCase
    {
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Method { get; set; } = string.Empty;
        public string Url { get; set; } = string.Empty;
        public long DateRequestedMs { get; set; }
        public string Nonce { get; set; } = string.Empty;
        public string PublicKey { get; set; } = string.Empty;
        public string PrivateKey { get; set; } = string.Empty;
        public string ContentHashAlgorithm { get; set; } = string.Empty;
        public string SignatureHashAlgorithm { get; set; } = string.Empty;
        public string? Body { get; set; }
        public List<ParityHeaderValue> HeaderValues { get; set; } = [];
        public string SigningContent { get; set; } = string.Empty;
        public string Signature { get; set; } = string.Empty;

        public ContentHashAlgorithm ContentHashAlgorithmValue => ContentHashAlgorithm switch
        {
            "SHA1" => HmacManager.Components.ContentHashAlgorithm.SHA1,
            "SHA256" => HmacManager.Components.ContentHashAlgorithm.SHA256,
            "SHA512" => HmacManager.Components.ContentHashAlgorithm.SHA512,
            _ => throw new ArgumentOutOfRangeException(nameof(ContentHashAlgorithm), ContentHashAlgorithm, null)
        };

        // The fixture names the digest, not the HMAC construction, because the TypeScript
        // client does — it passes "sha-256" as the hash of an "HMAC" WebCrypto algorithm.
        public SigningHashAlgorithm SigningHashAlgorithmValue => SignatureHashAlgorithm switch
        {
            "SHA1" => SigningHashAlgorithm.HMACSHA1,
            "SHA256" => SigningHashAlgorithm.HMACSHA256,
            "SHA512" => SigningHashAlgorithm.HMACSHA512,
            _ => throw new ArgumentOutOfRangeException(nameof(SignatureHashAlgorithm), SignatureHashAlgorithm, null)
        };

        // NUnit prints this for each generated case, so a failure names the case rather
        // than a positional index.
        public override string ToString() => Name;
    }

    public class ParityHeaderValue
    {
        public string Name { get; set; } = string.Empty;
        public string Value { get; set; } = string.Empty;
    }
}
